### ISSUE TITLE
Problem running lxd init: error: Unable to talk to LXD

### ISSUE THREAD

**Issue by falfaro** [conjure-up/conjure-up#1043]
## Report

conjure-up is running inside an LXD container. The host LXD machine is running 17.04 and the LXD container too. I have a shell script that spawns an LXD container named 'kubernetes' and inside it summons conjure-up to deploy a Kubernetes cluster. This is the output when running the script:

```
# ./kubernetes.sh                                                                                                                                                                                              
Creating kubernetes
Starting kubernetes
Get:1 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]
Hit:2 http://archive.ubuntu.com/ubuntu zesty InRelease                 
Get:3 http://archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]
Get:4 http://security.ubuntu.com/ubuntu zesty-security/main amd64 Packages [104 kB] 
Get:5 http://archive.ubuntu.com/ubuntu zesty-backports InRelease [89.2 kB]                    
Get:6 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages [8068 kB]               
Get:7 http://security.ubuntu.com/ubuntu zesty-security/main Translation-en [46.5 kB]
Get:8 http://security.ubuntu.com/ubuntu zesty-security/universe amd64 Packages [51.1 kB]                       
Get:9 http://archive.ubuntu.com/ubuntu zesty/universe Translation-en [4671 kB]                             
Get:10 http://security.ubuntu.com/ubuntu zesty-security/universe Translation-en [33.3 kB]
Get:11 http://archive.ubuntu.com/ubuntu zesty/multiverse amd64 Packages [154 kB]                        
Get:12 http://archive.ubuntu.com/ubuntu zesty/multiverse Translation-en [109 kB] 
Get:13 http://archive.ubuntu.com/ubuntu zesty-updates/main amd64 Packages [155 kB]     
Get:14 http://security.ubuntu.com/ubuntu zesty-security/multiverse amd64 Packages [1824 B]
Get:15 http://archive.ubuntu.com/ubuntu zesty-updates/main Translation-en [69.3 kB]
Get:16 http://archive.ubuntu.com/ubuntu zesty-updates/restricted amd64 Packages [2508 B]
Get:17 http://archive.ubuntu.com/ubuntu zesty-updates/restricted Translation-en [1444 B]
Get:18 http://archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages [83.1 kB]
Get:19 http://security.ubuntu.com/ubuntu zesty-security/multiverse Translation-en [1020 B]
Get:20 http://archive.ubuntu.com/ubuntu zesty-updates/universe Translation-en [48.3 kB]
Get:21 http://archive.ubuntu.com/ubuntu zesty-updates/multiverse amd64 Packages [10.5 kB]
Get:22 http://archive.ubuntu.com/ubuntu zesty-updates/multiverse Translation-en [5284 B]
Get:23 http://archive.ubuntu.com/ubuntu zesty-backports/main amd64 Packages [1488 B]
Get:24 http://archive.ubuntu.com/ubuntu zesty-backports/main Translation-en [664 B]
Get:25 http://archive.ubuntu.com/ubuntu zesty-backports/universe amd64 Packages [3104 B]
Get:26 http://archive.ubuntu.com/ubuntu zesty-backports/universe Translation-en [1396 B]
Fetched 13.9 MB in 2s (5561 kB/s)                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  squashfuse
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 17.5 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu zesty/universe amd64 squashfuse amd64 0.1.100-0ubuntu2 [17.5 kB]
Fetched 17.5 kB in 0s (581 kB/s)
Selecting previously unselected package squashfuse.
(Reading database ... 26658 files and directories currently installed.)
Preparing to unpack .../squashfuse_0.1.100-0ubuntu2_amd64.deb ...
Unpacking squashfuse (0.1.100-0ubuntu2) ...
Setting up squashfuse (0.1.100-0ubuntu2) ...
Processing triggers for man-db (2.7.6.1-2) ...
2017-07-19T14:01:30Z INFO cannot auto connect core:core-support-plug to core:core-support: (slot auto-connection), existing connection state "core:core-support-plug core:core-support" in the way
core (beta) 16-2.26.13 from 'canonical' installed
conjure-up (beta) 2.2.2 from 'canonical' installed
[info] Summoning canonical-kubernetes to localhost
[error] Problem running lxd init: error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: no such file or directory

[warning] Shutting down
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

This is the 'kubernetes.sh' script:

```
#!/bin/bash
lxc delete -f kubernetes
lxc launch ubuntu:17.04 -p default -p nested -p cache kubernetes
sleep 5s
lxc exec kubernetes -- apt-get update
lxc exec kubernetes -- apt-get install squashfuse
lxc exec kubernetes -- snap install core --beta
lxc exec kubernetes -- snap install conjure-up --classic --beta
lxc exec kubernetes -- sudo -u ubuntu -i conjure-up canonical-kubernetes localhost controller model
```

### Outside the LXD container

```
# lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/cache
- /1.0/containers/kubernetes

# lxc profile show nested
config:
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,openvswitch,nbd
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.mount.auto=sys:rw
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "true"
description: LXD container for nesting Docker/LXD
devices:
  aadisable:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
name: nested
used_by:
- /1.0/containers/kubernetes

# lxc profile show cache
config:
  boot.autostart: "true"
  user.user-data: |
    #cloud-config
    apt:
      proxy: http://cache:3142
description: Use apt-cacher container
devices: {}
name: cache
used_by:
- /1.0/containers/kubernetes

# lxc profile show cache
config:
  boot.autostart: "true"
  user.user-data: |
    #cloud-config
    apt:
      proxy: http://cache:3142
description: Use apt-cacher container
devices: {}
name: cache
used_by:
- /1.0/containers/kubernetes

# lxc network list
+--------+----------+---------+---------+
|  NAME  |   TYPE   | MANAGED | USED BY |
+--------+----------+---------+---------+
| eth0   | physical | NO      | 0       |
+--------+----------+---------+---------+
| lxdbr0 | bridge   | YES     | 2       |
+--------+----------+---------+---------+

# lxc network show lxdbr0
config:
  ipv4.address: 10.0.3.1/24
  ipv4.nat: "true"
  ipv6.address: none
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/cache
- /1.0/containers/kubernetes
managed: true

# lxc storage list
+---------+--------+---------+---------+
|  NAME   | DRIVER | SOURCE  | USED BY |
+---------+--------+---------+---------+
| default | zfs    | default | 6       |
+---------+--------+---------+---------+

# lxc storage show default
config:
  source: default
  zfs.pool_name: default
name: default
driver: zfs
used_by:
- /1.0/containers/cache
- /1.0/containers/kubernetes
- /1.0/images/2abede45754797ab1c64ddf294cd00a15ffbc6030f73d3c16c5aab0e46bd5a8b
- /1.0/images/7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
- /1.0/images/f50337be60f7fce4ddd71397285490115e208aeb37565b8d77529cb352cdad05
- /1.0/profiles/default
```

### Inside the LXD container

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which conjure-up.lxd
/snap/bin/conjure-up.lxd
$ juju version
2.2.2-zesty-amd64
$ conjure-up --version
conjure-up 2.2.2
$ conjure-up.lxd --version
2.14
$ conjure-up.lxc config show
LXD socket not found; is LXD installed and running?
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

Please attach tarball of **~/.cache/conjure-up**:

## Sosreport

Please attach a sosreport:

```
$ sudo apt install sosreport
$ sosreport

sosreport (version 3.4)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

canonical-kubernetes

## What provider (aws, maas, localhost, etc)?

localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
