### ISSUE TITLE
allow bundle fragments to specify new machines

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#1245]
I'd like to place applications on new machines when specified by a yaml fragment in a spell step.  Here's my env:
```
$ which juju
/snap/bin/juju

$ juju version
2.3-rc2-xenial-amd64

$ snap info juju
name:      juju
summary:   juju client
publisher: canonical
contact:   http://jujucharms.com
description: |
  Through the use of charms, juju provides you with shareable, re-usable, and
  repeatable expressions of devops best practices.
snap-id: e2CPHpB1fUxcKtCyJTsm5t3hN9axJ0yj
commands:
  - juju
tracking:    edge
installed:   2.3-rc2+develop-fbb8949 (3013) 52MB classic
refreshed:   2017-11-27 10:25:55 -0600 CST
channels:                                   
  stable:    2.2.6                   (2739) 25MB classic
  candidate: 2.3-rc1                 (2960) 52MB classic
  beta:      2.3-rc1                 (2960) 52MB classic
  edge:      2.3-rc2+develop-fbb8949 (3013) 52MB classic

$ which conjure-up
/snap/bin/conjure-up

$ conjure-up --version
conjure-up 2.4.1

$ snap info conjure-up
name:      conjure-up
summary:   Package runtime for conjure-up spells
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
snap-id: ijQR4HjYlTAmIjELJm5XCpNAqbDZWJ3h
commands:
  - conjure-up.conjure-down
  - conjure-up
  - conjure-up.juju
tracking:    beta
installed:   2.4.1-20171121.0211 (837) 82MB classic
refreshed:   2017-11-20 20:02:41 -0600 CST
channels:                                   
  stable:    2.4.1-20171121.0211      (837) 82MB classic
  candidate: 2.4.1-20171121.0211      (837) 82MB classic
  beta:      2.4.1-20171121.0211      (837) 82MB classic
  edge:      2.5-alpha1-20171122.1811 (842) 90MB classic

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

I conjure-up hadoop-processing with two new bundle fragments:

# elasticsearch / filebeat / graylog
```
services:
  apache2:
    charm: cs:xenial/apache2-22
    num_units: 1
    expose: true
    options:
      enable_modules: "headers proxy_html proxy_http"
    to:
      - "0"
  elasticsearch:
    charm: cs:xenial/elasticsearch-21
    num_units: 1
    options:
      firewall_enabled: false
    to:
      - "1"
  filebeat:
    charm: cs:xenial/filebeat-7
  graylog:
    charm: cs:xenial/graylog-7
    num_units: 1
    to:
      - "2"
  mongodb:
    charm: cs:xenial/mongodb-46
    num_units: 1
    to:
      - "2"
relations:
  - ["apache2:reverseproxy", "graylog:website"]
  - ["graylog:elasticsearch", "elasticsearch:client"]
  - ["graylog:mongodb", "mongodb:database"]
  - ["filebeat:elasticsearch", "elasticsearch:client"]
  - ["filebeat:beats-host", "namenode:juju-info"]
  - ["filebeat:beats-host", "slave:juju-info"]
machines:
  "0":
    series: "xenial"
  "1":
    series: "xenial"
  "2":
    series: "xenial"
```

# telegraf / prometheus / grafana
```
services:
  grafana:
    charm: cs:xenial/grafana-4
    num_units: 1
    expose: true
    to:
      - "0"
  prometheus:
    charm: cs:xenial/prometheus-5
    num_units: 1
    options:
      prometheus_registration_listen: '0.0.0.0'
    to:
      - "1"
  telegraf:
    charm: cs:xenial/telegraf-6
relations:
  - ["prometheus:grafana-source", "grafana:grafana-source"]
  - ["telegraf:prometheus-client", "prometheus:target"]
  - ["namenode:juju-info", "telegraf:juju-info"]
  - ["slave:juju-info", "telegraf:juju-info"]
machines:
  "0":
    series: "xenial"
  "1":
    series: "xenial"
```

When I check the architecture settings prior to deployment, I see that conjure-up is going to reuse machines [0|1|2] from the initial bundle deployment:

![screen shot 2017-11-27 at 2 25 58 pm](https://user-images.githubusercontent.com/4576822/33288085-a15a583c-d380-11e7-85fa-693ab928fc49.png)

Rather than reusing existing units, I expected the fragment machine definitions to be allocated as new machines.
