### ISSUE TITLE
bundle-add fragment hides remainder of applications

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1270]
```
applications:
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker"
    num_units: 3
    options:
      channel: 1.8/stable
    expose: true
    constraints: "instance-type=p2.xlarge"
```

Run with `conjure-up canonical-kubernetes --bundle-add fragment.yaml` and notice that only kubernetes-worker is shown. This occurs because some bundles still define "services" as their top level instead of the new default of "applications"
