### ISSUE TITLE
--add-bundle doesn't support local charms

### ISSUE THREAD

**Issue by hyperbolic2346** [conjure-up/conjure-up#1317]
running `conjure-up --bundle-add ./path/to/fragment.yaml canonical-kubernetes` with a fragment like:

```
services:
  kubeapi-load-balancer:
    charm: builds/kubeapi-load-balancer
  kubernetes-master:
    charm: builds/kubernetes-master
```
results in conjure-up trying to download from the charm store and error trying to find 'cs:builds/kubernetes-master'.
