### ISSUE TITLE
after-input doesnt run on steps with no viewable additional-input metadata

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#1364]
## What I'm trying to do

Create a cdk spell that will use `bundle-add` in an `after-input` step to reconfigure the `kubernetes-worker` stanza to set GPU constraints (`instance-type=pX`).

## What I did

Be me, on Darwin:

```
$ conjure-up --version
conjure-up 2.5.5
```

Attempt to include an `after-input` step (chmod'd 0755):

https://github.com/juju-solutions/spells/tree/feature/cdk-nvidia/canonical-kubernetes-nvidia/steps/00_process-providertype

Note that this step doesn't have `viewable: True` nor `additional-input` fields:

https://github.com/juju-solutions/spells/blob/feature/cdk-nvidia/canonical-kubernetes-nvidia/steps/00_process-providertype/metadata.yaml

Use a local spell dir with the above forked repo on the `feature/cdk-nvidia` branch with:

```
$ git clone -b feature/cdk-nvidia https://github.com/juju-solutions/spells.git /tmp/spells
$ conjure-up --nosync --spells-dir=/tmp/spells kubernetes
```

Select CDK+GPU, no addons, AWS, and the default flannel choice.  Notice the debug output does not say anything about running `canonical-kubernetes-nvidia/steps/00_process-providertype/after-input`.

## What I want

conjure-up to execute `after-input` even if there's no viewable additional input defined in the step metadata.

## What I got

conjure-up did not execute my `after-input` script.

## Colorful commentary

I tried quite a few permutations on the `00_process-providertype` step.  The only way I could get my `after-input` script to execute was to include `viewable: True` and an unused input into that step metadata:

```
title: Pre processing
description: Runs some pre processing requirements for certain providers
viewable: True
additional-input:
  - label: Wat
    key: NOTUSED
    type: choice
    default: gpu
    choices:
      - gpu
```

I could not get it to run without **both** `viewable` and `additional-input`.  Including these is most unfortunate because I don't actually want the user to see this `NOTUSED` key.
