### ISSUE TITLE
Conjure up won't bootstrap a named LXD cloud on Zesty

### ISSUE THREAD

**Issue by ChrisMacNaughton** [conjure-up/conjure-up#576]
conjure-up/kubernetes: [ERROR] conjure-up/kubernetes: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/conjureup/controllers/newcloud/gui.py", line 171, in render
    creds = Schema[app.current_cloud]
KeyError: 'lxd'

I manually created this clouds.yaml for other clouds:

```yaml
clouds:
  lxd:
    type: lxd
    config:
      apt-http-proxy: http://10.248.45.1:3142
      enable-os-upgrade: false

```
