### ISSUE TITLE
conjure-up error: Unable to find credentials for cloud looking for local-host

### ISSUE THREAD

**Issue by mbruzek** [conjure-up/conjure-up#807]
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available: i7 4-core CPU, 16MB of RAM, ~450GB free disk space.

What spell was selected?: kubernetes-core

What cloud provider was selected (this includes both MAAS and localhost)?: localhost

Please outline what commands were run to install and execute conjure-up: snap refresh --channel edge conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**: 

[conjure-up.log.zip](https://github.com/conjure-up/conjure-up/files/906201/conjure-up.log.zip)

Error occurred on 2017-04-07 I see no errors in the log for this day.w

Provide the output of the following commands:

```
mbruzek@pandora:~$ which -a juju
/snap/bin/juju
mbruzek@pandora:~$ which -a conjure-up
/snap/bin/conjure-up
mbruzek@pandora:~$ which -a lxd
/usr/bin/lxd
mbruzek@pandora:~$ juju version
2.2-beta3-yakkety-amd64
mbruzek@pandora:~$ conjure-up --version
conjure-up 2.2-beta3
mbruzek@pandora:~$ lxd --version
2.12
mbruzek@pandora:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Summary of problem:
I tried to conjure-up kubernetes core from the edge channel and got an error about credentials.
![conjure-up-2 1 2-beta3_error](https://cloud.githubusercontent.com/assets/6385185/24810517/1662beaa-1b88-11e7-90bd-d7aaa9b865e7.png)

**Comment by mbruzek** [comment]
Seems to be related to bootstrapping the localhost. I was able to use the same conjure-up with an already bootstrapped localhost. The deployment is getting further than before, not done, but past the credentials.

**Comment by battlemidget** [comment]
Yea I need to figure out why this is happening, they introduced some new credentials mechanism for localhost (im guessing for remote localhost eventually) and our logic isn't handling this quite well.

@johnsca do you mind looking into this?

**Comment by battlemidget** [comment]
Example credentials where the problem surfaced:

```
credentials:
  aws:
    default-credential: cdp
    default-region: us-west-1
    cdp:
      auth-type: access-key
      access-key: KEY
      secret-key: KEY//G3
    containers:
      auth-type: access-key
      access-key: KEY
      secret-key: KEY+KEY/KEY+KEY
    personal:
      auth-type: access-key
      access-key: KEY
      secret-key: KEY/KEY+KEY
  google:
    default-credential: work_bechmarking_gce
    default-region: us-central1
    mbruzek-work:
      auth-type: jsonfile
      file: /home/ubuntu/<redacted>.json
    work:
      auth-type: oauth2
      client-email: <redacted>
      client-id: <redacted>
      private-key: '-----BEGIN PRIVATE KEY-----\nKEY-----END 
      PRIVATE KEY-----\n'
      project-id: work
    work_bechmarking_gce:
      auth-type: jsonfile
      file: /home/user/<redacted>.json
```
