### ISSUE TITLE
better error handling in steps

### ISSUE THREAD

**Issue by NicolaiSchmid** [conjure-up/conjure-up#889]
## Report

- [x] Is conjure-up running inside a virtual machine?

## Version

```
which juju
/snap/bin/juju

which conjure-up
/snap/bin/conjure-up

which lxd
/usr/bin/lxd

juju version
2.1.2-xenial-amd64

conjure-up --version
conjure-up 2.1.5

lxd --version
2.13

lxc config show
config:
   core.https_address: '[::]'


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

```
## tar of .cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1005816/conjure-up.tar.gz)

## What Spell was Selected?
Openstack with LXD

## What provider (aws, maas, localhost, etc)?
Localhost

## Commands ran
```
snap install conjure-up --classic
conjure-up
```

## Additional Information
I was running a basic conjure-up for a localhost openstack with lxd, when after installing and starting all services, a screen came for selecting to upload images to cinder and deploying an ssh-key, etc.
After selecting all defaults it ran a few minutes. Then this stacktrace was printed, the command ran for another few minutes, and then I got my shell back
```
Exception in ev.run():
Traceback (most recent call last):
  File "/snap/conjure-up/257/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
Traceback (most recent call last):
  File "/snap/conjure-up/257/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.1.5', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/conjureup/app.py", line 369, in main
    EventLoop.run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/ubuntui/ev.py", line 82, in run
    cls.loop.run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/conjure-up/257/lib/python3.6/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
```

Thanks for your help!

**Comment by battlemidget** [comment]
Looks like an issue with the glance server itself:

```
WARNING: The client is falling back to v1 because the accessing to v2 failed. This behavior will be removed in future versions
Error finding address for http://10.0.8.237:9292/v1/images/detail?sort_key=name&sort_dir=asc&limit=20&property-name=trusty-lxd: Unable to establish connection to http://10.0.8.237:9292/v1/images/detail?sort_key=name&sort_dir=asc&limit=20&property-name=trusty-lxd
```

But we should handle this error more gracefully. What does `juju status --format yaml` give you?

**Comment by f7f7u7f7** [comment]
Hey, where did you find that log from above?

**Comment by f7f7u7f7** [comment]
```
juju status --format yaml
model:
  name: conjure-openstack-novalx-bf5
  controller: conjure-up-localhost-bfa
  cloud: localhost
  region: localhost
  version: 2.1.2
machines:
  "0":
    juju-status:
      current: started
      since: 16 May 2017 19:50:37+02:00
      version: 2.1.2
    dns-name: 10.0.8.226
    ip-addresses:
    - 10.0.8.226
    instance-id: juju-68d48f-0
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:49:03+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "1":
    juju-status:
      current: started
      since: 16 May 2017 19:48:32+02:00
      version: 2.1.2
    dns-name: 10.0.8.15
    ip-addresses:
    - 10.0.8.15
    instance-id: juju-68d48f-1
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:47:37+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "2":
    juju-status:
      current: started
      since: 16 May 2017 19:49:47+02:00
      version: 2.1.2
    dns-name: 10.0.8.9
    ip-addresses:
    - 10.0.8.9
    instance-id: juju-68d48f-2
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:48:22+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "3":
    juju-status:
      current: started
      since: 16 May 2017 19:51:00+02:00
      version: 2.1.2
    dns-name: 10.0.8.143
    ip-addresses:
    - 10.0.8.143
    instance-id: juju-68d48f-3
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:49:55+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "4":
    juju-status:
      current: started
      since: 16 May 2017 19:52:32+02:00
      version: 2.1.2
    dns-name: 10.0.8.26
    ip-addresses:
    - 10.0.8.26
    instance-id: juju-68d48f-4
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:50:57+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "5":
    juju-status:
      current: started
      since: 16 May 2017 19:53:55+02:00
      version: 2.1.2
    dns-name: 10.0.8.173
    ip-addresses:
    - 10.0.8.173
    instance-id: juju-68d48f-5
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:51:57+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "6":
    juju-status:
      current: started
      since: 16 May 2017 19:54:59+02:00
      version: 2.1.2
    dns-name: 10.0.8.206
    ip-addresses:
    - 10.0.8.206
    instance-id: juju-68d48f-6
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:53:00+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "7":
    juju-status:
      current: started
      since: 16 May 2017 19:55:54+02:00
      version: 2.1.2
    dns-name: 10.0.8.237
    ip-addresses:
    - 10.0.8.237
    instance-id: juju-68d48f-7
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:54:03+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "8":
    juju-status:
      current: started
      since: 16 May 2017 19:57:21+02:00
      version: 2.1.2
    dns-name: 10.0.8.92
    ip-addresses:
    - 10.0.8.92
    instance-id: juju-68d48f-8
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:55:19+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "9":
    juju-status:
      current: started
      since: 16 May 2017 19:59:20+02:00
      version: 2.1.2
    dns-name: 10.0.8.243
    ip-addresses:
    - 10.0.8.243
    instance-id: juju-68d48f-9
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:57:07+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "10":
    juju-status:
      current: started
      since: 16 May 2017 20:01:02+02:00
      version: 2.1.2
    dns-name: 10.0.8.250
    ip-addresses:
    - 10.0.8.250
    instance-id: juju-68d48f-10
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 19:58:59+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "11":
    juju-status:
      current: started
      since: 16 May 2017 20:03:05+02:00
      version: 2.1.2
    dns-name: 10.0.8.16
    ip-addresses:
    - 10.0.8.16
    instance-id: juju-68d48f-11
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 20:01:42+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "12":
    juju-status:
      current: started
      since: 16 May 2017 20:07:15+02:00
      version: 2.1.2
    dns-name: 10.0.8.190
    ip-addresses:
    - 10.0.8.190
    instance-id: juju-68d48f-12
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 20:05:09+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "13":
    juju-status:
      current: started
      since: 16 May 2017 20:08:47+02:00
      version: 2.1.2
    dns-name: 10.0.8.34
    ip-addresses:
    - 10.0.8.34
    instance-id: juju-68d48f-13
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 20:07:21+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "14":
    juju-status:
      current: started
      since: 16 May 2017 20:13:39+02:00
      version: 2.1.2
    dns-name: 10.0.8.122
    ip-addresses:
    - 10.0.8.122
    instance-id: juju-68d48f-14
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 20:11:14+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
  "15":
    juju-status:
      current: started
      since: 16 May 2017 20:15:34+02:00
      version: 2.1.2
    dns-name: 10.0.8.67
    ip-addresses:
    - 10.0.8.67
    instance-id: juju-68d48f-15
    machine-status:
      current: running
      message: Running
      since: 16 May 2017 20:13:43+02:00
    series: xenial
    hardware: arch=amd64 cores=0 mem=0M
applications:
  ceph-mon:
    charm: cs:ceph-mon-9
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: ceph-mon
    charm-rev: 9
    exposed: false
    application-status:
      current: active
      message: Unit is ready and clustered
      since: 17 May 2017 11:37:41+02:00
    relations:
      client:
      - glance
      - nova-compute
      mon:
      - ceph-mon
      osd:
      - ceph-osd
      radosgw:
      - ceph-radosgw
    units:
      ceph-mon/0:
        workload-status:
          current: active
          message: Unit is ready and clustered
          since: 17 May 2017 11:37:41+02:00
        juju-status:
          current: executing
          message: running update-status hook
          since: 17 May 2017 11:37:33+02:00
          version: 2.1.2
        machine: "0"
        public-address: 10.0.8.226
      ceph-mon/1:
        workload-status:
          current: active
          message: Unit is ready and clustered
          since: 17 May 2017 11:32:45+02:00
        juju-status:
          current: executing
          message: running update-status hook
          since: 17 May 2017 11:37:36+02:00
          version: 2.1.2
        leader: true
        machine: "1"
        public-address: 10.0.8.15
      ceph-mon/2:
        workload-status:
          current: active
          message: Unit is ready and clustered
          since: 17 May 2017 11:36:46+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:36:47+02:00
          version: 2.1.2
        machine: "2"
        public-address: 10.0.8.9
    version: 10.2.6
  ceph-osd:
    charm: cs:ceph-osd-241
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: ceph-osd
    charm-rev: 241
    exposed: false
    application-status:
      current: active
      message: Unit is ready (1 OSD)
      since: 17 May 2017 11:37:40+02:00
    relations:
      mon:
      - ceph-mon
    units:
      ceph-osd/0:
        workload-status:
          current: active
          message: Unit is ready (1 OSD)
          since: 17 May 2017 11:37:40+02:00
        juju-status:
          current: executing
          message: running update-status hook
          since: 17 May 2017 11:37:32+02:00
          version: 2.1.2
        machine: "3"
        public-address: 10.0.8.143
      ceph-osd/1:
        workload-status:
          current: active
          message: Unit is ready (1 OSD)
          since: 17 May 2017 11:35:35+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:35:38+02:00
          version: 2.1.2
        machine: "4"
        public-address: 10.0.8.26
      ceph-osd/2:
        workload-status:
          current: active
          message: Unit is ready (1 OSD)
          since: 17 May 2017 11:37:36+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:37:39+02:00
          version: 2.1.2
        leader: true
        machine: "5"
        public-address: 10.0.8.173
    version: 10.2.6
  ceph-radosgw:
    charm: cs:ceph-radosgw-247
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: ceph-radosgw
    charm-rev: 247
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:37:02+02:00
    relations:
      cluster:
      - ceph-radosgw
      identity-service:
      - keystone
      mon:
      - ceph-mon
    units:
      ceph-radosgw/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:37:02+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:37:04+02:00
          version: 2.1.2
        leader: true
        machine: "6"
        open-ports:
        - 80/tcp
        public-address: 10.0.8.206
    version: 10.2.6
  glance:
    charm: cs:glance-256
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: glance
    charm-rev: 256
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:36:51+02:00
    relations:
      amqp:
      - rabbitmq-server
      ceph:
      - ceph-mon
      cluster:
      - glance
      identity-service:
      - keystone
      image-service:
      - nova-cloud-controller
      - nova-compute
      shared-db:
      - mysql
    units:
      glance/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:36:51+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:36:54+02:00
          version: 2.1.2
        leader: true
        machine: "7"
        open-ports:
        - 9292/tcp
        public-address: 10.0.8.237
    version: 12.0.0
  keystone:
    charm: cs:keystone-265
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: keystone
    charm-rev: 265
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:33:56+02:00
    relations:
      cluster:
      - keystone
      identity-service:
      - ceph-radosgw
      - glance
      - neutron-api
      - nova-cloud-controller
      - openstack-dashboard
      shared-db:
      - mysql
    units:
      keystone/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:33:56+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:34:12+02:00
          version: 2.1.2
        leader: true
        machine: "8"
        open-ports:
        - 5000/tcp
        public-address: 10.0.8.92
    version: 9.2.0
  lxd:
    charm: cs:lxd-10
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: lxd
    charm-rev: 10
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:33:02+02:00
    relations:
      lxd:
      - nova-compute
      lxd-migration:
      - lxd
    subordinate-to:
    - nova-compute
    version: 2.0.9
  mysql:
    charm: cs:percona-cluster-250
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: percona-cluster
    charm-rev: 250
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:34:34+02:00
    relations:
      cluster:
      - mysql
      shared-db:
      - glance
      - keystone
      - neutron-api
      - nova-cloud-controller
    units:
      mysql/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:34:34+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:35:03+02:00
          version: 2.1.2
        leader: true
        machine: "9"
        public-address: 10.0.8.243
    version: 5.6.34-26.19
  neutron-api:
    charm: cs:neutron-api-250
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: neutron-api
    charm-rev: 250
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:34:18+02:00
    relations:
      amqp:
      - rabbitmq-server
      cluster:
      - neutron-api
      identity-service:
      - keystone
      neutron-api:
      - nova-cloud-controller
      neutron-plugin-api:
      - neutron-gateway
      - neutron-openvswitch
      shared-db:
      - mysql
    units:
      neutron-api/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:34:18+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:34:57+02:00
          version: 2.1.2
        leader: true
        machine: "10"
        open-ports:
        - 9696/tcp
        public-address: 10.0.8.250
    version: 8.4.0
  neutron-gateway:
    charm: cs:neutron-gateway-234
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: neutron-gateway
    charm-rev: 234
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:34:06+02:00
    relations:
      amqp:
      - rabbitmq-server
      cluster:
      - neutron-gateway
      neutron-plugin-api:
      - neutron-api
      quantum-network-service:
      - nova-cloud-controller
    units:
      neutron-gateway/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:34:06+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:34:19+02:00
          version: 2.1.2
        leader: true
        machine: "11"
        public-address: 10.0.8.16
    version: 8.4.0
  neutron-openvswitch:
    charm: cs:neutron-openvswitch-240
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: neutron-openvswitch
    charm-rev: 240
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:35:19+02:00
    relations:
      amqp:
      - rabbitmq-server
      neutron-plugin:
      - nova-compute
      neutron-plugin-api:
      - neutron-api
    subordinate-to:
    - nova-compute
    version: 8.4.0
  nova-cloud-controller:
    charm: cs:nova-cloud-controller-294
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: nova-cloud-controller
    charm-rev: 294
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:36:39+02:00
    relations:
      amqp:
      - rabbitmq-server
      cloud-compute:
      - nova-compute
      cluster:
      - nova-cloud-controller
      identity-service:
      - keystone
      image-service:
      - glance
      neutron-api:
      - neutron-api
      quantum-network-service:
      - neutron-gateway
      shared-db:
      - mysql
    units:
      nova-cloud-controller/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:36:39+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:36:47+02:00
          version: 2.1.2
        leader: true
        machine: "12"
        open-ports:
        - 8774/tcp
        public-address: 10.0.8.190
    version: 13.1.3
  nova-compute:
    charm: cs:nova-compute-266
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: nova-compute
    charm-rev: 266
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:34:04+02:00
    relations:
      amqp:
      - rabbitmq-server
      ceph:
      - ceph-mon
      cloud-compute:
      - nova-cloud-controller
      compute-peer:
      - nova-compute
      image-service:
      - glance
      lxd:
      - lxd
      neutron-plugin:
      - neutron-openvswitch
    units:
      nova-compute/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:34:04+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:34:18+02:00
          version: 2.1.2
        leader: true
        machine: "13"
        public-address: 10.0.8.34
        subordinates:
          lxd/0:
            workload-status:
              current: active
              message: Unit is ready
              since: 17 May 2017 11:33:02+02:00
            juju-status:
              current: idle
              since: 17 May 2017 11:33:05+02:00
              version: 2.1.2
            leader: true
            upgrading-from: cs:lxd-10
            public-address: 10.0.8.34
          neutron-openvswitch/0:
            workload-status:
              current: active
              message: Unit is ready
              since: 17 May 2017 11:35:19+02:00
            juju-status:
              current: idle
              since: 17 May 2017 11:35:28+02:00
              version: 2.1.2
            leader: true
            upgrading-from: cs:neutron-openvswitch-240
            public-address: 10.0.8.34
    version: 13.1.3
  ntp:
    charm: cs:ntp-17
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: ntp
    charm-rev: 17
    exposed: false
    application-status:
      current: waiting
      message: waiting for machine
      since: 16 May 2017 20:08:27+02:00
    relations:
      ntp-peers:
      - ntp
  openstack-dashboard:
    charm: cs:openstack-dashboard-245
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: openstack-dashboard
    charm-rev: 245
    exposed: true
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:36:48+02:00
    relations:
      cluster:
      - openstack-dashboard
      identity-service:
      - keystone
    units:
      openstack-dashboard/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:36:48+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:36:52+02:00
          version: 2.1.2
        leader: true
        machine: "14"
        open-ports:
        - 80/tcp
        - 443/tcp
        public-address: 10.0.8.122
    version: 9.1.1
  rabbitmq-server:
    charm: cs:rabbitmq-server-61
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: rabbitmq-server
    charm-rev: 61
    exposed: false
    application-status:
      current: active
      message: Unit is ready
      since: 17 May 2017 11:34:44+02:00
    relations:
      amqp:
      - glance
      - neutron-api
      - neutron-gateway
      - neutron-openvswitch
      - nova-cloud-controller
      - nova-compute
      cluster:
      - rabbitmq-server
    units:
      rabbitmq-server/0:
        workload-status:
          current: active
          message: Unit is ready
          since: 17 May 2017 11:34:44+02:00
        juju-status:
          current: idle
          since: 17 May 2017 11:35:08+02:00
          version: 2.1.2
        leader: true
        machine: "15"
        open-ports:
        - 5672/tcp
        public-address: 10.0.8.67
    version: 3.5.7

```
